### ISSUE TITLE
Incompatibility with RQ >= 0.7.0

### ISSUE THREAD

**Issue by bbc2** [jezdez/Flask-RQ2#12]
Since version 0.7.0 of RQ, I get the following error when starting a worker:

```
> ./app/manage.py rq worker
Traceback (most recent call last):
  File "./app/manage.py", line 96, in <module>
    manager.run()
  File "/home/bertrand/code/web-findings/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/bertrand/code/web-findings/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/bertrand/code/web-findings/venv/lib/python3.5/site-packages/flask_rq2/script.py", line 42, in __call__
    return self.run(*args, **kwargs)
  File "/home/bertrand/code/web-findings/venv/lib/python3.5/site-packages/flask_rq2/script.py", line 179, in run
    queues=queues or self.rq.queues,
TypeError: <flask_rq2.script.WorkerCommand object at 0x7fac62dd5630>: worker() missing 1 required positional argument: 'connection_class'
```

It looks like this is due to https://github.com/nvie/rq/pull/741 that added the `connection_class` parameter to the `worker` command.

Note that Flask-RQ2 only requires `rq>=0.6.0`.  I suppose this requirement should be updated until the incompatibility is fixed.

**Comment by jlev** [comment]
I found this issue via the following error, which was also resolved by restricting rq<0.7.0 in my requirements.txt

```
$ python manager.py rq worker
Traceback (most recent call last):
  File "manager.py", line 29, in <module>
    manager.run()
  File "/Users/jlev/Code/FftF/votebot-forms/.venv/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/Users/jlev/Code/FftF/votebot-forms/.venv/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/Users/jlev/Code/FftF/votebot-forms/.venv/lib/python2.7/site-packages/flask_rq2/script.py", line 43, in __call__
    return self.run(*args, **kwargs)
  File "/Users/jlev/Code/FftF/votebot-forms/.venv/lib/python2.7/site-packages/flask_rq2/script.py", line 197, in run
    queues=queues or self.rq.queues,
TypeError: <flask_rq2.script.WorkerCommand object at 0x109a2cbd0>: worker() takes exactly 17 arguments (16 given) 
```
