### ISSUE TITLE
NoRedisConnectionException on starting app

### ISSUE THREAD

**Issue by noenthu** [jezdez/Flask-RQ2#2]
When running python app.py on the attached app.py. I'm running into a NoRedisConnectionException 

when RQ(app) is called - the init_app method calls connect 
stack.top is None and no rq_redis is returned

```
      @property
      def connection(self):
          ctx = stack.top
          if ctx is not None:
              if not hasattr(ctx, 'rq_redis'):
                  ctx.rq_redis = self._connect()
              return ctx.rq_redis
```

using python 3.4.2

Flask-RQ2 (16.1.1)
Flask (0.11)
rq (0.6.0)
rq-scheduler (0.7.0)

```

from flask import Flask
from flask_rq2 import RQ
from datetime import datetime, timedelta

app = Flask(__name__)

app.config['RQ_REDIS_URL'] = 'redis://localhost:6379/0'

rq = RQ(app)

@rq.job
def add(x,y):
    return x+y

#add.schedule(timedelta(seconds=60), 1,2)
add.queue(1,2)

if __name__ == '__main__':
    app.run()

```

```
Traceback (most recent call last):
  File "app.py", line 15, in <module>
    add.queue(1,2)
  File "/Users/cchowdvi/.virtualenvs/py3tfsheroku/lib/python3.4/site-packages/flask_rq2/helpers.py", line 45, in queue
    return self.rq.get_queue(self.queue_name).enqueue_call(
  File "/Users/cchowdvi/.virtualenvs/py3tfsheroku/lib/python3.4/site-packages/flask_rq2/app.py", line 324, in get_queue
    connection=self.connection,
  File "/Users/cchowdvi/.virtualenvs/py3tfsheroku/lib/python3.4/site-packages/rq/queue.py", line 59, in **init**
    self.connection = resolve_connection(connection)
  File "/Users/cchowdvi/.virtualenvs/py3tfsheroku/lib/python3.4/site-packages/rq/connections.py", line 73, in resolve_connection
    raise NoRedisConnectionException('Could not resolve a Redis connection')
rq.connections.NoRedisConnectionException: Could not resolve a Redis connection
```

**Comment by dveselov** [comment]
Have same problem.
If you want to queue/schedule tasks at startup, you must do it within application context:
```python
# app.py

def schedule_tasks():
    from tasks import my_periodic_task
    with app.app_context():
        my_periodic_task.schedule()

schedule_tasks()
```

**Comment by jezdez** [comment]
Hm, odd. Will look into this..

**Comment by furritos** [comment]
Just to add with @dveselov post, same thing with workers...

```
with app.app_context():
    default_worker = rq.get_worker()
    default_worker.work()
```

**Comment by hugohonorem** [comment]
I am still having this issue. 
```

from flask import Flask
from flask_rq2 import RQ
from datetime import datetime, timedelta

app = Flask(__name__)

app.config['RQ_REDIS_URL'] = 'redis://localhost:6379'

rq = RQ(app)

@rq.job
def add(x,y):
    return x+y

add.schedule(timedelta(seconds=60), 1,2)

if __name__ == '__main__':
    app.run()

```

**Comment by italomaia** [comment]
I also hit that problem. The plugin is initialized, and the exception is thrown. 

package version flask-rq2==17.0

**Comment by italomaia** [comment]
@jezdez can we help?

**Comment by zgoda** [comment]
I'm getting into this trying to run worker from cli using bare `python manage.py rq worker`. If I schedule task to run as cron with app context as @dveselov suggests I'm getting other kind of error:

```
$ python manage.py rq worker
Traceback (most recent call last):
  File "manage.py", line 35, in <module>
    cli()
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/flask_rq2/cli.py", line 40, in new_func
    return func(rq, ctx, *args, **kwargs)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/flask_rq2/cli.py", line 138, in worker
    queues=queues or rq.queues,
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/rq/cli/cli.py", line 175, in worker
    worker_class = import_attribute(worker_class)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/rq/utils.py", line 150, in import_attribute
    module = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named backend_zkw.app
```

Flask is 0.12.2, I have customized Click-based launcher (`manage.py`). Application itself runs fine, I just can't start worker to process tasks.

So far I tried:

* schedule tasks at module level and import the tasks module in blueprint's `__init__.py` (ImportError)
* same as above but import blueprint module in app factory as late as possible (NoRedisConnection)
* schedule tasks in app factory after all app initialization is done (ImportError)

**Comment by zgoda** [comment]
Does the PR https://github.com/nvie/rq/pull/786 affect this issue? If so, upgrading RQ dependency to `>=0.8` should solve the problem for good (PR #25 covers this).
