### ISSUE TITLE
Not able to start worker

### ISSUE THREAD

**Issue by zgoda** [jezdez/Flask-RQ2#32]
Flask is 0.12.2, I have customized launcher, basically normal `FlaskGroup` with couple additional commands

If I try to start worker using `rq worker` I'm getting following error:

```
$ python manage.py rq worker
Traceback (most recent call last):
  File "manage.py", line 35, in <module>
    cli()
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/flask_rq2/cli.py", line 40, in new_func
    return func(rq, ctx, *args, **kwargs)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/flask_rq2/cli.py", line 138, in worker
    queues=queues or rq.queues,
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/rq/cli/cli.py", line 175, in worker
    worker_class = import_attribute(worker_class)
  File "/home/jazg/v/zkw/local/lib/python2.7/site-packages/rq/utils.py", line 150, in import_attribute
    module = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named backend_zkw.app
```

Application `zkw` otherwise runs fine and I can enqueue jobs.

**Comment by zgoda** [comment]
`rq info` works fine:

```
$ python manage.py rq info
default      |█ 1
1 queues, 1 jobs total

0 workers, 1 queues

Updated: 2017-09-21 11:52:08.777488
```

**Comment by zgoda** [comment]
Confirmed that customized launcher does not have any impact on this, generic `flask rq worker` fails in the same way.

**Comment by zgoda** [comment]
Either google had problem indexing https://github.com/jezdez/Flask-RQ2/issues/6 or I was not able to formulate my search phrase correctly. ;)
