### ISSUE TITLE
unable to start rq worker on windows?

### ISSUE THREAD

**Issue by syncml** [jezdez/Flask-RQ2#39]
Hi
  When I run `python manage.py rq worker `
 Then throw error message: `AttributeError: 'module' object has no attribute 'fork'`
 i's not supported on windows platform?
 Thank you

```
E:\workspace2\H-Service>python manage.py rq worker
D:\Anaconda2\lib\site-packages\flask_cache\jinja2ext.py:33: ExtDeprecationWarnin
g: Importing flask.ext.cache is deprecated, use flask_cache instead.
  from flask.ext.cache import make_template_fragment_key
21:16:39 RQ worker u'rq:worker:NOTEBOOK66.7220' started, version 0.6.0
21:16:39 Cleaning registries for queue: default
21:16:39
21:16:39 *** Listening on ?[32mdefault?[39;49;00m...
21:17:19 ?[32mdefault?[39;49;00m: ?[34mapp.jobs.send_message('a', 'b')?[39;49;00m (324bec07-ed74-4d65-9504-71621ce97159)
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    manager.run()
  File "D:\Anaconda2\lib\site-packages\flask_script\__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "D:\Anaconda2\lib\site-packages\flask_script\__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "D:\Anaconda2\lib\site-packages\flask_rq2\script.py", line 42, in __call__
    return self.run(*args, **kwargs)
  File "D:\Anaconda2\lib\site-packages\flask_rq2\script.py", line 180, in run
    queues=queues or self.rq.queues,
  File "D:\Anaconda2\lib\site-packages\rq\cli\cli.py", line 204, in worker
    w.work(burst=burst)
  File "D:\Anaconda2\lib\site-packages\rq\worker.py", line 450, in work
    self.execute_job(job, queue)
  File "D:\Anaconda2\lib\site-packages\rq\worker.py", line 511, in execute_job
    child_pid = os.fork()
AttributeError: 'module' object has no attribute 'fork'

```
manage.py:

```
import os
from flask_rq2.script import RQManager
from flask_script import Manager

from app import create_app, rq

app = create_app(os.getenv('FLASK_CONFIG') or 'default')
manager = Manager(app)
manager.add_command('rq', RQManager(rq))

if __name__ == '__main__':
    manager.run()
```

**Comment by jezdez** [comment]
[RQ](https://github.com/nvie/rq) doesn't support Windows out of the box due to the way it [forks the worker processes](https://github.com/nvie/rq/blob/df571e14fd4dabfe8f76a27231d709a8c9a72e3f/rq/worker.py#L579-L589) using [`os.fork`](https://docs.python.org/3/library/os.html#os.fork). There isn't anything I can do about this since this is a downstream project. Please file an issue against RQ if you require this feature.
