### ISSUE TITLE
ImportError: No module named backend_dist.manage when using Flask-Script

### ISSUE THREAD

**Issue by flowstack** [jezdez/Flask-RQ2#6]
Hi Everyone,

Thanks for contributing this project. It is extremely useful.

I'm struggling to get it working with Flask-Script however. Running

> python manage.py rq

lists all the commands correctly.

However, as soon as I attempt to start a worker with:

> python manage.py rq worker

I am hit with:

```
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    manager.run()
  File "/Users/name/Documents/Development/venv/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/Users/name/Documents/Development/venv/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/Users/name/Documents/Development/venv/lib/python2.7/site-packages/flask_rq2/script.py", line 42, in __call__
    return self.run(*args, **kwargs)
  File "/Users/name/Documents/Development/venv/lib/python2.7/site-packages/flask_rq2/script.py", line 179, in run
    queues=queues or self.rq.queues,
  File "/Users/name/Documents/Development/venv/lib/python2.7/site-packages/rq/cli/cli.py", line 175, in worker
    worker_class = import_attribute(worker_class)
  File "/Users/name/Documents/Development/venv/lib/python2.7/site-packages/rq/utils.py", line 151, in import_attribute
    module = importlib.import_module(module_name)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named backend_dist.manage
```

Looking through `flask_rq2.app.py` I noticed a `module_path` is being set on line 189.

> self.module_path = 'flask_rq2.backend_%s' % app.name

I do have an application in `dist.manage` but I suspect flask_rq2 may be looking for it in the wrong place. My directory structure is:

```
manage.py
dist
- manage
-- __init__.py
-- *.py
```

Any help much appreciated.

(I know this probably isn't a bug, so this may not be the best way of asking for help, but thanks anyway!)

**Comment by jezdez** [comment]
Ah I see, there are two things going on here:

1) your app probably uses `__name__` as the first parameter when it's instantiated so it's internally `dist.manage`. This isn't ideal since it means Flask and some extensions won't be able to use the name of the application package as a prefix to find things, e.g. in a traceback. I encourage you to read the "About the First Parameter" section on http://flask.pocoo.org/docs/0.11/api/#application-object for some background.

2) Flask-RQ2 stupidly assumes that app names don't contain dots, which is a bug you've seen. I'll fix it here, but as a work around you should be able to set the app's name (in your `dist.manage` package) to just `dist` for example.

Thanks for the report!

**Comment by flowstack** [comment]
Thank you. I've read up on the `__name__` parameter and can now see what was happening. Thanks for the help. Really appreciate you taking the time to write this module and respond.
